import { useState } from 'react';
import { getSession } from './cloudSync';

// ── AI Reading card ──────────────────────────────────────────────────────
// Sends a compact chart summary to the /api/interpret Worker route (Cloudflare
// Workers AI) and renders the interpretation. Requires a signed-in session;
// the access token is attached so the Worker can authorize the request.
const FOCUSES = [
  { key: 'overview', label: 'Personality' },
  { key: 'career', label: 'Career' },
  { key: 'relationships', label: 'Relationships' },
  { key: 'current', label: 'Current Dasha' },
];

export default function AIReading({ summary, disabled }) {
  const [focus, setFocus] = useState('overview');
  const [loading, setLoading] = useState(false);
  const [text, setText] = useState('');
  const [error, setError] = useState('');

  const generate = async () => {
    setError('');
    setText('');
    setLoading(true);
    try {
      const session = await getSession();
      const res = await fetch('/api/interpret', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}),
        },
        body: JSON.stringify({ summary, focus }),
      });
      const ct = res.headers.get('content-type') || '';
      if (!ct.includes('application/json')) {
        // Usually means the API route isn't available (e.g. local `vite` dev
        // without the Worker). Give an actionable hint instead of raw HTML.
        throw new Error('AI endpoint not available here. It runs on the deployed site (Cloudflare Worker).');
      }
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || `Request failed (${res.status})`);
      setText(data.text || '(no response)');
    } catch (e) {
      setError(e.message || 'Something went wrong.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="ai-reading glass-subcard spacing-bottom">
      <div className="ai-reading-head">
        <h3 className="card-subtitle" style={{ margin: 0 }}>✨ AI Astrologer <span className="ai-beta">beta</span></h3>
        <p className="section-description" style={{ margin: '4px 0 0' }}>
          A Vedic interpretation of your chart, generated by Cloudflare Workers AI.
        </p>
      </div>

      <div className="ai-focus-row">
        {FOCUSES.map(f => (
          <button
            key={f.key}
            type="button"
            className={`ai-focus-btn${focus === f.key ? ' active' : ''}`}
            onClick={() => setFocus(f.key)}
            disabled={loading}
          >{f.label}</button>
        ))}
      </div>

      <button className="btn btn-primary ai-generate" onClick={generate} disabled={disabled || loading}>
        {loading ? 'Consulting the stars…' : 'Generate reading'}
      </button>

      {disabled && !loading && (
        <p className="ai-hint">Generate a birth chart first to enable AI readings.</p>
      )}
      {error && <div className="ai-error">⚠ {error}</div>}
      {text && (
        <div className="ai-result">
          {text.split(/\n{2,}/).map((para, i) => <p key={i}>{para.trim()}</p>)}
          <p className="ai-disclaimer">
            AI-generated for reflection and entertainment. Astrology is not scientifically validated;
            treat readings as food for thought, not advice.
          </p>
        </div>
      )}
    </div>
  );
}
